name: CI

on:
  push:
    branches:
      - develop

jobs:
  build-test-push-scan:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_SETTINGS_MODULE: config.settings.test
      PYTHONUNBUFFERED: 1
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devops-coding-challenge
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      CELERY_BROKER_URL: redis://localhost:6379/0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
          pip install -r requirements/local.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: pytest --disable-warnings

      - name: Run flake8
        run: flake8 .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} -f compose/local/django/Dockerfile .

      - name: Push Docker image to GHCR
        run: docker push $IMAGE_NAME:${{ github.sha }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
